name: Build LaTeX Documents

on:
  push:
    paths:
    - '**.tex'
    - '**.bib'
    - '.github/workflows/build-latex.yml'
  pull_request:
    paths:
    - '**.tex'
    - '**.bib'
    - '.github/workflows/build-latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            deliverable1.tex

      - name: Save outputs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: ./*.pdf