name: Compile LaTeX Documents

on:
  push:
    paths:
    - '**.tex'
    - '**.bib'
    - '.github/workflows/compile-latex.yml'

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory:
            papers
          root_file: |
            deliverable1.tex

      - name: Upload output PDFs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: papers
          path: papers/*.pdf
