name: Format Python Code

on:
  pull_request:
    paths:
    - '**.py'
    - '.github/workflows/formatting.yml'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: '. --check'
